### ISSUE TITLE
Does not work with Spell Checker add-on

### ISSUE THREAD

**Issue by Hudziak68** [Arthur-Milchior/anki-Multi-column-edit-window#10]
I already had the Spell Checker add-on (Glutanimate) and then opened Anki after having installed the Multi-column add-on. 

I then opened the browse window with both of these add-ons enabled, but got the error below. I disabled the Multi-column add-on, restarted Anki, then opened the browse window without an error message.

I also tried enabling the Multi-column add-on + disabling the Spell Checker add-on, and opening the browse window, and that was successful, too. So it seems like the Multi-column add-on and the Spell Checker add-on are not compatible with each other.

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.20 (47a1bf8b) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.15.2
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-02-20 18:14:35
Add-ons possibly involved: Spell Checker, Customize Keyboard Shortcuts, Advanced note editor Multi-column Frozen fields LaTeXs result in editor, Advanced Browser, Opening the same window multiple time

Caught exception:
Traceback (most recent call last):
  File "aqt/main.py", line 982, in onBrowse
  File "/Users/User1/Library/Application Support/Anki2/addons21/354407385/multiple.py", line 68, in open
    return function(name,*args)
  File "/Users/User1/Library/Application Support/Anki2/addons21/354407385/multiple.py", line 80, in openMany
    instance = creator(*args)
  File "/Users/User1/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 276, in __init__
    origInit(self, mw)
  File "</Applications/Anki.app/Contents/MacOS/decorator.pyc:decorator-gen-148>", line 2, in __init__
  File "anki/hooks.py", line 530, in decorator_wrapper
  File "anki/hooks.py", line 521, in repl
  File "aqt/browser.py", line 581, in __init__
  File "</Applications/Anki.app/Contents/MacOS/decorator.pyc:decorator-gen-142>", line 2, in cs_browser_setupEditor
  File "anki/hooks.py", line 530, in decorator_wrapper
  File "anki/hooks.py", line 521, in repl
  File "/Users/User1/Library/Application Support/Anki2/addons21/24411424/custom_shortcuts.py", line 311, in cs_browser_setupEditor
    self.editor = Editor(self.mw, self.form.fieldsArea, self)
  File "</Applications/Anki.app/Contents/MacOS/decorator.pyc:decorator-gen-198>", line 2, in __init__
  File "anki/hooks.py", line 530, in decorator_wrapper
  File "anki/hooks.py", line 521, in repl
  File "/Users/User1/Library/Application Support/Anki2/addons21/2064123047/multiColumnEdit.py", line 33, in __init__
    old_init(self, *args, **kwargs)
  File "aqt/editor.py", line 83, in __init__
  File "/Users/User1/Library/Application Support/Anki2/addons21/24411424/custom_shortcuts.py", line 179, in cs_editor_setupShortcuts
    runHook("setupEditorShortcuts", cuts, self)
  File "anki/hooks.py", line 475, in runHook
  File "/Users/User1/Library/Application Support/Anki2/addons21/spell_checker/editor.py", line 194, in onSetupShortcuts
    cuts.append(("F6", self.web.toggleSpellcheck))
AttributeError: 'EditorWebView' object has no attribute 'toggleSpellcheck'

**Comment by Arthur-Milchior** [comment]
Yeah, I need to change how this add-on work. There is nothing easy I can do. Sorry

**Comment by Hudziak68** [comment]
No problem, just wanted to let you know. Thanks!

**Comment by ijgnd** [comment]
I only did a very brief test but for me "spell checker" seems to work with the latest version of [Multi-column note editor](https://ankiweb.net/shared/info/3491767031) (and [Frozen-field compatible with other add-on](https://ankiweb.net/shared/info/389392894)).

@Hudziak68: Can you confirm this.

**Comment by Hudziak68** [comment]
Looks like it's working, thank you!

**Comment by Arthur-Milchior** [comment]
Thanks for letting me know @ijgnd. Happy to see that the work I did to make everything compatible with everything else works even on things I did forget to check
